### ISSUE TITLE
Arcade High Score Sync

### ISSUE THREAD

**Issue by ver151set** [blakekl/rpie-preservatives#8]
Any way to have the save the hiscore files for arcade games? In my roms/arcade folder there is a folder for mame2003 and fbneo, in those is a very small .hi file for each game thats saves leaderboards

**Comment by blakekl** [comment]
yeah, that shouldn't be too hard to do. I know some games create other resources in those folders that can be quite large, but I think the .hi file is just for high scores. I'll take a look at this.

**Comment by blakekl** [comment]
@ver151set I've never used fbneo and the docs for it don't really say where the hi scores are stored. Could you share what the fbneo directory looks like? 
For mame, it looks like the high scores are actually stored in the nvram files.

**Comment by ver151set** [comment]
Hiscore files using game 1941 as example, all games will save the .hi file with scores and some also save the .nv

Mame2003 /home/pi/RetroPie/roms/arcade/mame2003/hi/1941.hi
/home/pi/RetroPie/roms/arcade/mame2003/nvram/1941.nv

Mame2003-plus /home/pi/RetroPie/roms/arcade/mame2003-plus/hi/1941.hi
/home/pi/RetroPie/roms/arcade/mame2003-plus/nvram/1941.nv

Fbneo /home/pi/RetroPie/roms/arcade/fbneo/1941.hi (also stores .nv files in this directory)

**Comment by blakekl** [comment]
I think I have this fixed. I put #7 in the same branch though, so if we get the redream stuff figured out, I can merge them both into master and create a new release.
